%% Formal inverse-sensing mesh verification for layer-local pyro assembly.
% Each mesh is assembled and solved independently through run_meet_static.
% Target displacements are obtained by exact linear scaling of that mesh's
% own pressure-probe solution; no COMSOL or literature value calibrates it.
clear; clc;
paths = setup_paths();

meshDivisions = [10; 15; 20; 30];
targetDisplacementsMm = [0.5; 1.0; 2.0];
outDir = fullfile(paths.workbench, 'outputs', 'code_closure', 'inverse_sensing');
if ~isfolder(outDir), mkdir(outDir); end

rows = table();
rawResults = cell(numel(meshDivisions), 1);
for meshIndex = 1:numel(meshDivisions)
    mesh = meshDivisions(meshIndex);
    caseFile = fullfile(paths.cases, 'validation_mesh', sprintf( ...
        'Thermal_CFFF_U_Vf0.6-%dx%d-10layer.txt', mesh, mesh));
    if ~isfile(caseFile)
        error('inverse_mesh:MissingCase', 'Missing generated case: %s', caseFile);
    end

    tag = sprintf('inverse_structural_pyro_%dx%d', mesh, mesh);
    probe = run_meet_static(caseFile, 'elastic', ...
        'LoadScale', -15000, 'OutTag', tag, 'SolveSensors', true, ...
        'UseCache', false, 'Quiet', true);
    rawResults{meshIndex} = probe;

    for targetIndex = 1:numel(targetDisplacementsMm)
        targetMm = targetDisplacementsMm(targetIndex);
        scale = targetMm / abs(probe.wCenter_mm);
        row = table(mesh, targetMm, probe.wCenter_mm, scale, ...
            probe.electric_span * scale, probe.magnetic_span * scale, ...
            probe.theta_span_K * scale, string(probe.inputFile), ...
            string(probe.output_mat), string(probe.solver_revision), ...
            string(probe.solve_status), string(probe.sensor_status), ...
            string(probe.centerProbeMethod), ...
            probe.mechanical_thermal_relative_residual, ...
            probe.mechanical_thermal_backward_error, ...
            probe.mechanical_thermal_rcond_estimate, ...
            probe.sensor_relative_residual, probe.sensor_backward_error, ...
            probe.sensor_rcond_estimate, probe.correct_pyro_assembly, ...
            'VariableNames', {'mesh_divisions','target_w_mm', ...
            'probe_w_center_mm','linear_scale','electric_span_V', ...
            'magnetic_span_A','theta_span_K','input_file','raw_mat_file', ...
            'solver_revision','solve_status','sensor_status', ...
            'center_probe_method','mechanical_thermal_relative_residual', ...
            'mechanical_thermal_backward_error', ...
            'mechanical_thermal_rcond_estimate','sensor_relative_residual', ...
            'sensor_backward_error','sensor_rcond_estimate','layer_local_pyro'});
        rows = [rows; row]; %#ok<AGROW>
    end
end

rows.run_timestamp(:) = string(datestr(now, 30));
outCsv = fullfile(outDir, 'matlab_inverse_structural_pyro_mesh.csv');
outMat = fullfile(outDir, 'matlab_inverse_structural_pyro_mesh_raw.mat');
writetable(rows, outCsv);
save(outMat, 'rows', 'rawResults', 'meshDivisions', 'targetDisplacementsMm');
fprintf('MATLAB_INVERSE_STRUCTURAL_PYRO_MESH_COMPLETE,%s\n', outCsv);
disp(rows(rows.target_w_mm == 0.5, {'mesh_divisions','electric_span_V', ...
    'magnetic_span_A','probe_w_center_mm'}));
