%% Representative R=0.4 m curvature-gradient mesh check at 20x20 and 30x30.
clear; clc;
paths = setup_paths();
rows = struct('mesh', {}, 'mode', {}, 'radius_m', {}, 'load_case', {}, ...
    'w_center_mm', {}, 'electric_span', {}, 'magnetic_span', {}, ...
    'theta_span_K', {}, 'center_node_id', {}, 'center_coord_1', {}, ...
    'center_coord_2', {}, 'center_coord_3', {}, 'case_file', {}, ...
    'solver_revision', {}, 'solve_status', {}, 'sensor_status', {}, ...
    'mechanical_thermal_relative_residual', {}, 'sensor_relative_residual', {}, ...
    'status', {});

for mesh = [20, 30]
    for mode = ["U", "X"]
        filename = sprintf('Thermal_CFFF_%s_Vf0.6_R0.4m-%dx%d-10layer.txt', ...
            mode, mesh, mesh);
        caseFile = fullfile(paths.cases, 'curvature_fg', sprintf('%dx%d', mesh, mesh), filename);
        if ~isfile(caseFile)
            error('run_matlab_curvature_fg_meshcheck:MissingCase', 'Missing %s', caseFile);
        end
        baseTag = sprintf('curvmesh_%d_%s_R0p4', mesh, mode);
        elastic = run_meet_static(caseFile, 'elastic', ...
            'LoadScale', -15000, 'OutTag', [baseTag '_elastic'], ...
            'SolveSensors', true, 'UseCache', true);
        electro = run_meet_static(caseFile, 'electro', ...
            'Volt', 300, 'OutTag', [baseTag '_electro'], ...
            'SolveSensors', true, 'UseCache', true);
        magneto = run_meet_static(caseFile, 'magneto', ...
            'Magnetic', 200, 'OutTag', [baseTag '_magneto'], ...
            'SolveSensors', true, 'UseCache', true);
        assert_formal_meet_evidence(elastic, [baseTag '_elastic']);
        assert_formal_meet_evidence(electro, [baseTag '_electro']);
        assert_formal_meet_evidence(magneto, [baseTag '_magneto']);
        rows(end+1) = make_row(mesh, mode, caseFile, "elastic", elastic); %#ok<SAGROW>
        rows(end+1) = make_row(mesh, mode, caseFile, "electro", electro); %#ok<SAGROW>
        rows(end+1) = make_row(mesh, mode, caseFile, "magneto", magneto); %#ok<SAGROW>
    end
end

results = struct2table(rows);
pilotPath = fullfile(paths.workbench, 'outputs', 'paper-20260715-fgmee', ...
    'experiments', 'curvature_fg', 'curvature_fg_pilot_10x10.csv');
pilot = readtable(pilotPath, 'TextType', 'string');
pilot = pilot(pilot.radius_m == 0.4, :);
assert_formal_meet_evidence(pilot, 'curvature_fg_pilot_10x10.csv R=0.4 rows');
pilotRows = table(pilot.mesh, pilot.mode, pilot.radius_m, pilot.load_case, ...
    pilot.w_center_mm, pilot.electric_span, pilot.magnetic_span, pilot.theta_span_K, ...
    pilot.center_node_id, pilot.center_coord_1, pilot.center_coord_2, pilot.center_coord_3, ...
    pilot.case_file, pilot.solver_revision, pilot.solve_status, pilot.sensor_status, ...
    pilot.mechanical_thermal_relative_residual, pilot.sensor_relative_residual, ...
    repmat("completed_pilot_layer_local_pyro_v3", height(pilot), 1), ...
    'VariableNames', results.Properties.VariableNames);
allLevels = [pilotRows; results];
allLevels = sortrows(allLevels, {'mode','load_case','mesh'});
allLevels.w_change_from_previous_pct = nan(height(allLevels),1);
allLevels.electric_change_from_previous_pct = nan(height(allLevels),1);
allLevels.magnetic_change_from_previous_pct = nan(height(allLevels),1);
for mode = ["U", "X"]
    for loadCase = ["elastic", "electro", "magneto"]
        idx = find(allLevels.mode == mode & allLevels.load_case == loadCase);
        for j = 2:numel(idx)
            previous = idx(j-1); current = idx(j);
            allLevels.w_change_from_previous_pct(current) = relchange( ...
                allLevels.w_center_mm(current), allLevels.w_center_mm(previous));
            allLevels.electric_change_from_previous_pct(current) = relchange( ...
                allLevels.electric_span(current), allLevels.electric_span(previous));
            allLevels.magnetic_change_from_previous_pct(current) = relchange( ...
                allLevels.magnetic_span(current), allLevels.magnetic_span(previous));
        end
    end
end

outDir = fullfile(paths.workbench, 'outputs', 'paper-20260715-fgmee', ...
    'experiments', 'curvature_fg');
outRaw = fullfile(outDir, 'curvature_fg_meshcheck_R0p4_raw.csv');
outConv = fullfile(outDir, 'curvature_fg_meshcheck_R0p4_convergence.csv');
writetable(results, outRaw);
writetable(allLevels, outConv);
fprintf('CURVATURE_FG_MESHCHECK_COMPLETED,%s\n', outConv);
disp(allLevels(:, {'mesh','mode','load_case','w_center_mm', ...
    'w_change_from_previous_pct','electric_change_from_previous_pct', ...
    'magnetic_change_from_previous_pct'}));

function row = make_row(mesh, mode, caseFile, loadCase, result)
coord = result.centerCoord;
row = struct('mesh', mesh, 'mode', string(mode), 'radius_m', 0.4, ...
    'load_case', string(loadCase), 'w_center_mm', result.wCenter_mm, ...
    'electric_span', result.electric_span, 'magnetic_span', result.magnetic_span, ...
    'theta_span_K', result.theta_span_K, 'center_node_id', result.centerNodeId, ...
    'center_coord_1', coord(1), 'center_coord_2', coord(2), ...
    'center_coord_3', coord(3), 'case_file', string(caseFile), ...
    'solver_revision', string(result.solver_revision), ...
    'solve_status', string(result.solve_status), ...
    'sensor_status', string(result.sensor_status), ...
    'mechanical_thermal_relative_residual', ...
    result.mechanical_thermal_relative_residual, ...
    'sensor_relative_residual', result.sensor_relative_residual, ...
    'status', "completed_layer_local_pyro_v3");
end

function value = relchange(current, previous)
value = 100 * abs(current - previous) / max(abs(current), eps);
end
