%% Re-run the true R=0.4 m 20x20 U/X cases after template-radius audit.
clear; clc;
paths = setup_paths();
rows = struct('mesh', {}, 'mode', {}, 'radius_m', {}, 'load_case', {}, ...
    'w_center_mm', {}, 'electric_span', {}, 'magnetic_span', {}, ...
    'theta_span_K', {}, 'center_node_id', {}, 'center_coord_1', {}, ...
    'center_coord_2', {}, 'center_coord_3', {}, 'case_file', {}, ...
    'solver_revision', {}, 'solve_status', {}, 'sensor_status', {}, ...
    'mechanical_thermal_relative_residual', {}, 'sensor_relative_residual', {}, ...
    'status', {});
mesh = 20;
for mode = ["U", "X"]
    filename = sprintf('Thermal_CFFF_%s_Vf0.6_R0.4m-20x20-10layer.txt', mode);
    caseFile = fullfile(paths.cases, 'curvature_fg', '20x20', filename);
    if ~isfile(caseFile)
        error('run_matlab_curvature_fg_radiusfix20:MissingCase', 'Missing %s', caseFile);
    end
    baseTag = sprintf('curvmesh_radiusfix20_%s_R0p4', mode);
    elastic = run_meet_static(caseFile, 'elastic', ...
        'LoadScale', -15000, 'OutTag', [baseTag '_elastic'], ...
        'SolveSensors', true, 'UseCache', true);
    electro = run_meet_static(caseFile, 'electro', ...
        'Volt', 300, 'OutTag', [baseTag '_electro'], ...
        'SolveSensors', true, 'UseCache', true);
    magneto = run_meet_static(caseFile, 'magneto', ...
        'Magnetic', 200, 'OutTag', [baseTag '_magneto'], ...
        'SolveSensors', true, 'UseCache', true);
    assert_formal_meet_evidence(elastic, [baseTag '_elastic']);
    assert_formal_meet_evidence(electro, [baseTag '_electro']);
    assert_formal_meet_evidence(magneto, [baseTag '_magneto']);
    rows(end+1) = make_row(mode, caseFile, "elastic", elastic); %#ok<SAGROW>
    rows(end+1) = make_row(mode, caseFile, "electro", electro); %#ok<SAGROW>
    rows(end+1) = make_row(mode, caseFile, "magneto", magneto); %#ok<SAGROW>
end
results = struct2table(rows);
outDir = fullfile(paths.workbench, 'outputs', 'paper-20260715-fgmee', ...
    'experiments', 'curvature_fg');
outCsv = fullfile(outDir, 'curvature_fg_meshcheck_R0p4_20_radiusfixed.csv');
writetable(results, outCsv);
fprintf('CURVATURE_FG_RADIUSFIX20_COMPLETED,%s\n', outCsv);
disp(results(:, {'mesh','mode','load_case','w_center_mm','electric_span','magnetic_span'}));

function row = make_row(mode, caseFile, loadCase, result)
coord = result.centerCoord;
row = struct('mesh', 20, 'mode', string(mode), 'radius_m', 0.4, ...
    'load_case', string(loadCase), 'w_center_mm', result.wCenter_mm, ...
    'electric_span', result.electric_span, 'magnetic_span', result.magnetic_span, ...
    'theta_span_K', result.theta_span_K, 'center_node_id', result.centerNodeId, ...
    'center_coord_1', coord(1), 'center_coord_2', coord(2), ...
    'center_coord_3', coord(3), 'case_file', string(caseFile), ...
    'solver_revision', string(result.solver_revision), ...
    'solve_status', string(result.solve_status), ...
    'sensor_status', string(result.sensor_status), ...
    'mechanical_thermal_relative_residual', ...
    result.mechanical_thermal_relative_residual, ...
    'sensor_relative_residual', result.sensor_relative_residual, ...
    'status', "completed_radius_audited_layer_local_pyro_v3");
end
