function line = format_material_line(layerIdx, p)
%FORMAT_MATERIAL_LINE  One MATERIAL row for thermal MEET input (27 fields).

    line = sprintf([ ...
        '%d\t%.3E\t%.3E\t%.3E\t%.3E\t%.3E\t%.3E\t%.3E\t%.3E\t%.3E\t' ...
        '%.3E\t%.3E\t%.3E\t%.3E\t%.3E\t%.3E\t%.3E\t%.3E\t%.3E\t%.3E\t' ...
        '%.3E\t%.3E\t%.3E\t%.3E\t%.3E\t%.3E\t%d'], ...
        layerIdx, p.E1, p.E2, p.v12, p.v23, p.G12, p.G13, p.G23, ...
        p.d31, p.d32, p.angle, p.hE, p.q31, p.q32, p.g33, p.k33, p.r33, ...
        p.A1, p.A2, p.PyroE, p.PyroM, p.Cv, p.HC, p.Density, p.zC1, p.zC2, p.IsSmtLay);
end
